### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hyochan** [hyochan/github-stats#21]
## List of ideas
- [ ] Track APIs historically on a yearly basis
- [ ] Connect people based on shared interests
- [ ] More detailed stats when signing it
